### ISSUE TITLE
Input and environment params become `any` if no schema is passed

### ISSUE THREAD

**Issue by danielweinmann** [seasonedcc/domain-functions#115]
```ts
const foo = makeDomainFunction()(({ inputFoo }, { envFoo }) => {
  return inputFoo + envFoo
})
````

I would expect the code above to fail to type-check but it works because both input and environment are of type `any`. Is it possible to make them `never` when no schema is passed?

I just had an unexpected runtime error because I was destructuring a key from the environment but had forgotten to pass the env schema to `makeDomainFunction`.

**Comment by diogob** [comment]
The current runtime logic for no schemas is different for input and environment:
- input: when no schema is passed we assume the input should be undefined.
- environment: when no schema is passed we assume the environment is some `Record<PropertyKey, unknown>`.

So the `any` on `envFoo` above jives with this notion, since descruturing from an `unknown` will yield you `any` (which should be a red flag on its own).

`inputFoo` however, should not have type-checked since it will take only undefined.

**Comment by danielweinmann** [comment]
What's the reasoning behind assuming `Record<PropertyKey, unknown>` for environments?
